spring:
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.harithafashion: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173
  delivery:
    charge: 1
    free-threshold: 999999

razorpay:
  key-id: rzp_live_T2us6h38UBrNiN
  key-secret: bSHV10TxIvwjQ9gWj75b0vNA
  webhook-secret: ''
